import { test, expect } from '@playwright/test';

test.describe('Task Management', () => {
    // Login before tests
    test.beforeEach(async ({ page }) => {
        await page.goto('/login');
        await page.fill('input[type="email"]', 'ahmet@4flow.com');
        await page.fill('input[type="password"]', 'test123');
        await page.click('button[type="submit"]');
        await expect(page).toHaveURL(/\/dashboard/);

        // Go to the first project
        // Wait for projects to load
        await page.waitForSelector('a[href^="/board/"]');
        await page.click('a[href^="/board/"] >> nth=0');
    });

    test('should create a new task', async ({ page }) => {
        // Click "Görev Ekle" button usually in the header or list
        // Ensure we are on the board page
        await expect(page).toHaveURL(/\/board\//);

        // Look for "Görev Ekle" button (Assuming it's a button with text "Görev Ekle" or a plus icon)
        // Based on previous knowledge, there might be a "Yeni Görev" button or similar.
        // Let's use a generic selector or text locators.
        // If the UI has specific IDs it's better.

        // Open "Yeni görev ekle" modal
        await page.getByText('Yeni görev ekle').click();

        // Fill task title using the correct placeholder or name attribute
        const taskTitle = `E2E Test Task ${Date.now()}`;
        await page.fill('input[name="title"]', taskTitle);

        // Fill description (optional but good for testing)
        await page.fill('textarea[name="description"]', 'Generated by Playwright');

        // Submit the form
        await page.click('button[type="submit"]');

        // Verify toast appears
        await expect(page.getByText('Görev oluşturuldu')).toBeVisible();

        // Reload to ensure data is fetched
        await page.reload();

        // Wait for the table to load
        await page.waitForSelector('span:has-text("Görev")', { state: 'visible' });

        // Verify task appears in the list
        await expect(page.getByText(taskTitle)).toBeVisible({ timeout: 10000 });
    });
});
